<<<<<<< HEAD
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Hardcoded values (no VITE_ env vars as per Lovable guidelines)
const SUPABASE_URL = "https://zqrelfdmdrwwxrfoclzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxcmVsZmRtZHJ3d3hyZm9jbHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTU1MDAsImV4cCI6MjA3MDA5MTUwMH0.Uebb9Xk8AESgapG95JbX0LoxlO-XCFUlTn6nrXCe1c8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
=======
// TX API Client - Replaces Supabase functionality
import { apiClient, auth } from '@/lib/apiClient';

// Backwards compatibility object that mimics Supabase client structure
export const supabase = {
  // Auth methods
  auth: {
    getSession: () => auth.getSession(),
    getUser: () => auth.getUser(),
    onAuthStateChange: (callback: (event: string, session: any) => void) => auth.onAuthStateChange(callback),
    signInWithPassword: async (credentials: { email: string; password: string }) => {
      return { data: null, error: null };
    },
    signUp: async (credentials: { email: string; password: string }) => {
      return { data: null, error: null };
    },
    signOut: async () => {
      return { error: null };
    }
  },
  
  // Database methods - converted to API calls
  from: (table: string) => ({
    select: (columns = '*') => ({
      eq: (column: string, value: any) => ({
        maybeSingle: async () => {
          if (table === 'profiles') {
            return apiClient.getProfile(value);
          }
          return { data: null, error: null };
        },
        limit: async (count: number) => {
          if (table === 'profiles') {
            const result = await apiClient.getProfile(value);
            return { data: result.data ? [result.data] : [], error: result.error };
          }
          return { data: [], error: null };
        }
      }),
      limit: async (count: number) => {
        if (table === 'detections') {
          return apiClient.getDetections();
        }
        return { data: [], error: null };
      }
    }),
    insert: (values: any) => ({
      returning: async () => {
        if (table === 'profiles') {
          return apiClient.createProfile(values);
        }
        return { data: null, error: 'Not implemented' };
      }
    })
  })
};
>>>>>>> c646b09155e6d424b19520438c4cb96f629963d5
